# Copyright (c) 2017 - present Adobe Systems Incorporated. All rights reserved.

# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://opensource.org/licenses/MIT

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resources:
- name: repo-code
  type: git
  icon: github
  source:
    uri: git@git.corp.adobe.com:Target-ops/tf-manage.git
    private_key: ((/UI/infrastructure/generic_users/tgtuibot.tgtuibot-gitcorp-ssh-key))
    branch: master

- name: alpine-docker-image
  icon: docker
  type: docker-image
  source:
    tag: 3-alpine
    username: ((/UI/infrastructure/generic_users/tgtuibot.user))
    password: ((/UI/infrastructure/generic_users/tgtuibot.artifactory_corp_api_key))
    repository: docker-asr-release.dr.corp.adobe.com/behance/docker-base

- name: tfm-docker-image
  icon: docker
  type: docker-image
  source:
    username: ((/UI/infrastructure/generic_users/tgtuibot.user))
    password: ((/UI/infrastructure/generic_users/tgtuibot.artifactory_uw2_api_key))
    repository: docker-tf-manage-release.dr-uw2.adobeitc.com/tf-manage

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: alpine-docker-image
      trigger: true
    - get: repo-code
      trigger: true
  - put: tfm-docker-image
    params:
      build: repo-code

- name: validate
  serial: true
  public: true
  plan:
  - get: repo-code
    trigger: true
    passed: [publish]
  - task: print-contents
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          username: tgtuibot
          password: ((/UI/infrastructure/generic_users/tgtuibot.artifactory_uw2_api_key))
          repository: docker-tf-manage-release.dr-uw2.adobeitc.com/tf-manage
      run:
        path: sh
        args:
        - -c
        - |
          tree -L 3 /opt/terraform
          tf
          terraform version
