resources:
- name: tfm-code
  type: git
  icon: github
  source:
    uri: git@git.corp.adobe.com:Target-ops/tf-manage.git
    private_key: ((/UI/infrastructure/generic_users/tgtuibot.data.tgtuibot-gitcorp-ssh-key))
    branch: develop
    ignore_paths: [concourse/]

- name: tfm-pipeline
  type: git
  icon: github
  source:
    uri: git@git.corp.adobe.com:Target-ops/tf-manage.git
    private_key: ((/UI/infrastructure/generic_users/tgtuibot.data.tgtuibot-gitcorp-ssh-key))
    branch: develop
    paths: [concourse/]


- name: tfm-docker-image
  icon: docker
  type: docker-image
  source:
    username: tgtuibot
    password: ((/UI/infrastructure/generic_users/tgtuibot.data.artifactory_api_key))
    repository: docker-tf-manage-release.dr-uw2.adobeitc.com/tf-manage

jobs:
- name: reconfigure-self
  public: true
  serial: true
  plan:
    - get: tfm-pipeline
      params:
        submodules: none
      trigger: true
    - set_pipeline: build-docker-image
      file: tfm-pipeline/concourse/pipelines/docker-image-tfm.yaml

- name: publish
  public: true
  serial: true
  plan:
  - get: tfm-code
    trigger: true
  - put: tfm-docker-image
    params:
      build: tfm-code

- name: validate
  serial: true
  public: true
  plan:
  - get: tfm-code
    trigger: true
    passed: [publish]
  - task: print-contents
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          username: tgtuibot
          password: ((/UI/infrastructure/generic_users/tgtuibot.data.artifactory_api_key))
          repository: docker-tf-manage-release.dr-uw2.adobeitc.com/tf-manage
      run:
        path: sh
        args:
        - -c
        - |
          yum -y install tree &&
          tree -L 3 /opt
